### PR TITLE
Add support for PHP-Parser 4.0

### PR DESCRIPTION
**Pull request by nikic**
Looks like no code changes were necessary.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. I'd be interested to know who is still needing this library on newer versions of PHP?

**Comment by GrahamCampbell** [comment]
That is, referring to "ClassPreloader" as "this library".

**Comment by GrahamCampbell** [comment]
I had basically anticipated that 3.2.0 would be the last ever release. :)

**Comment by nikic** [comment]
@GrahamCampbell No idea really, I just saw that this is a dependent library with a large number of downloads (>10M), so likely to cause dependency conflicts. If it's not being used anymore, I guess that concern would be moot.

**Comment by GrahamCampbell** [comment]
At a guess, I'd say more than 99% of those downloads are from versions of the Laravel Framework that are no longer supported. The only currently supported versions are Laravel 5.5 LTS, and 5.6 stable, neither of which depend on this project, since they all PHP 7 only. :)

**Comment by GrahamCampbell** [comment]
I'll sleep on this, and decide what to do next week. Thanks for all your work on PHP Parser, and on PHP!

**Comment by nikic** [comment]
Closing this as the change does not seem to be useful, per previous comments.

**Pull request closed without merging**
